### ISSUE TITLE
SAML - Is there any easy way to implement it with Snipe-IT?

### ISSUE THREAD

**Issue by cwhittl** [snipe/snipe-it#542]
We have just purchased OneLogin service and would love to use it with SnipeIT.
Thanks!
##

**Comment by snipe** [comment]
Not out of the box, but we can look into how much work it would be to integrate.

**Comment by hughevans** [comment]
SAML might be a better option than LDAP/AD integration. A lot of people are moving in this direction. More webby.

**Comment by snipe** [comment]
Looks like OneLogin has a package, which could make this easier. https://github.com/onelogin/php-saml

**Comment by hughevans** [comment]
I’ve used their Ruby package and it’s excellent. My PHP is very rusty, otherwise I’d help out.

**Comment by vsposato** [comment]
@snipe what about http://packalyst.com/packages/package/aacotroneo/laravel-saml2? It appears to be based on php-saml, but is already a package.

**Comment by snipe** [comment]
Yeah, we were looking at that one recently too.

**Comment by richardcorder** [comment]
Hi there, we're also using Single Sign On - OKTA is the tool we are using.
Our benefit would not be the SSO aspect (we only have two technicians so no big deal) for us the really cool thing would be the automatic user account creation & removal that this could offer.  This would save us time, but most importantly keep the user names created and synced with our HR user database.

**Comment by delize** [comment]
Would also like to bump this, as this would be great for us. We use Okta. We also use AD/LDAP, so using either isn't a huge problem for us.

**Comment by Stevenlastax** [comment]
Hey guys, we're using OKTA too, and we're interested in having SAML active too.

**Comment by NicholasBentley** [comment]
+1 for SAML - this is literally the only tool out there that does asset management right & would be killer with SAML integration

**Comment by Kilo1548** [comment]
Totally agree!  +1 for SAML integration.

**Comment by v3rb4l** [comment]
Any updates on potential SAML integration? We are a school district that utilizes RapidIdentity (by Identity Automation), which is in the same vein as Okta and some of the other services mentioned in this thread.  SAML would be a fantastic excellent addition.

**Comment by snipe** [comment]
If there were updates, we'd publish them to this ticket. The API is currently higher priority than SAML integration, but it's still on the list.

**Comment by v3rb4l** [comment]
Completely understand. Thank you for the response.

**Comment by zezuladp** [comment]
+1 for SAML. Also thank you for your amazing work

**Comment by markwangpd** [comment]
+1 for SAML! So far this platform is awesome, great work.

**Comment by jonflaire** [comment]
+1 for SAML -- as we look to implement this, the decision would be way easier to justify if SAML support was supported.

**Comment by avcarrillo** [comment]
We are using the cloud hosted Snipe-IT solution. LDAP is not an option for us, so +1 for SAML

**Comment by dhayc17** [comment]
Hi excuse my ignorance,

We have signed up for cloud hosted version of Snipe-IT - so far its awesome.

I'm trying to configure LDAP integration, all fields are filled out but having a connection issue.

Do I need to have an instance of my Active Directory in the cloud (AWS, Azure) for this to work as my instance of Snipe-IT is cloud hosted ?

**Comment by snipe** [comment]
Hi @dhayc17 - you do need it to be accessible via your hosted IP, which usually means poking a hole in your firewall for the static IP. If you contact support via email, we can give you your hosted static IP

**Comment by dhayc17** [comment]
Hi @snipe 

Thank you for the quick reply!

I've raised that via support so I'll wait to hear back :) 

I'll then allow traffic from the external IP provided hopefully that does the trick!

Thanks,
Dan

**Comment by TheVakman** [comment]
+1 SAML would be awesome for us to setup SSO for SnipeIT in our environment.

**Comment by ajcollett** [comment]
SAML and CAS would be amazing!

**Comment by Genae** [comment]
+1 for SAML

**Comment by Zorlin** [comment]
+1 for SAML, particularly for G Suite.

**Comment by kallaics-liferay** [comment]
+1 SAML

**Comment by hofnarrr** [comment]
+1 for SAML. Thanks!

**Comment by grantemsley** [comment]
I'll throw another +1 in here for SAML.

I use ADFS with Microsoft's multifactor authentication.  It lets me do nice things like not require MFA from our office, only from outside, and optionally automatically log people in from domain joined computers.

**Comment by pageb018** [comment]
Would love SAML support. Hope is comes soon!

**Comment by snipe** [comment]
It is unlikely that we will implement this soon. You can check out the `REMOTE_USER` still tat was added recently though. https://github.com/snipe/snipe-it/pull/5142

**Comment by raleighguevarra** [comment]
@snipe Is it also possible to use Google (GMail) to login? I'm using G Suite and had a way to login to WordPress site using only the registered gmail. Hope to be also implemented with Snipe-IT. Thank you so much in advance.

**Comment by snipe** [comment]
@raleighguevarra That's not currently possible

**Comment by MMore** [comment]
+1 for SAML

**Comment by mjsilva** [comment]
An alternative for now might be if you're using okta you can just use their [SWA](https://support.okta.com/help/Documentation/Knowledge_Article/Overview-of-Managing-Apps-and-SSO-1573170842) to replay AD username and password. This doesn't solve provisioning or if you user directory is not AD but it's something.

**Comment by rysiekpl** [comment]
Any status on this? SAML would be very useful for us.

**Comment by snipe** [comment]
SAML support was implemented in this PR via REMOTE_USER: https://github.com/snipe/snipe-it/pull/5142

Future SSO development will probably be in the direction of OAuth, not SAML.

**Comment by roberthurricane** [comment]
+1 for SAML integration. We work with a lot of enterprises that are moving towards SAML, none of them are discussing OAuth at all.

**Comment by rysiekpl** [comment]
Well, we'd love one or the other, although we do consider [OpenID Connect](https://openid.net/connect/) (which is based on OAuth) to be more manageable and easier to implement than SAML.

**Comment by snipe** [comment]
@rysiekpl SAML was introduced in https://github.com/snipe/snipe-it/pull/5142

**Comment by rysiekpl** [comment]
> @rysiekpl SAML was introduced in #5142

No, it wasn't. What was introduced is a way to authenticate a user via REMOTE_USER. This is useful, and we are already using it, but it is nowhere *near* implementing SAML (or OpenID Connect). Both are way more expressive than just "this is the authenticated user"; specifically, the pull request does not implement any way to handle [SAML assertions](https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language#Assertions).

This is the core functionality of SAML and *actually* implementing it would mean that not only the user database can be kept outside of SnipeIT, but also *group memberships*. Which simplifies access management greatly in large organizations with dozens of different systems.

So no, SAML was not implemented via REMOTE_USER because there is simply no way to implement SAML via a simple "this is the authenticated user" statement.

**Comment by katyayayni** [comment]
So Team, With OneLogin can we enable SSO on SNIPE IT with SAML introduced in #5142, Kindly help clarify.

**Comment by timwsuqld** [comment]
@snipe Can we please have this reopened. #5142 DID NOT fix this as it only introduced REMOTE_USER and not SAML login.

**Comment by marcosiebecke** [comment]
+1 SAML

**Comment by webbexpert** [comment]
Hi Everyone! Wrote support and this ticket was reopened much to public demand!

Specifically, the feature being asked for here is best demonstrated by the workflow found here: https://developers.onelogin.com/saml

This type of integration will allow enterprise IT managers to setup a trust with snipe-it such that users are either provisioned, and optionally, authenticated to the application. 

Typically, the parameters required to implement this feature to setup a Service Provider (Snipe-IT):

- IDP Entity NameId
- IDP X509Certificate
- IDP SingleSignOnServiceUrl
- IDP SingleLogoutServiceUrl

(optional: consume a metadata URL to retrieve the above information)

Snipe-IT would store this information, and when SAMLResponses is received from the IDP, snipe-it would compare the x509Certificate to the signature in the IDP POST to your SP Endpoint in Snipe-IT

More information on this workflow, with examples, are included in the link above.

**Comment by claytonolley** [comment]
+1 SAML... Okta user here...

**Comment by rhanooman** [comment]
+1 for Okta

**Comment by inkaudio** [comment]
+1 for SAML. Using OneLogin.

**Comment by Ben11111111** [comment]
+1 for SAML

**Comment by jsheridan1** [comment]
+1 for SAML. Using OneLogin.

**Comment by ChrisPVella** [comment]
+1 for SAML/OpenID/OAuth. Using Azure AD.

**Comment by loetmann** [comment]
+1 for SAML  SAML support and demand for SPs is growing.

**Comment by scraane** [comment]
+1 for SAML support!

**Comment by ewancolyer1** [comment]
_another +1 for SAML_

**Comment by josephvaughan** [comment]
another +1 for SAML.  What kind of help do you need to get this done?

**Comment by dhoer** [comment]
Really, 4 years and no progress on this.  Can't you just state on your main page that you no longer want to compete in asset management market?

**Comment by dhayc17** [comment]
Agreed. We have moved on

Thanks,
Daniel
________________________________

**Comment by rhanooman** [comment]
@snipe a response would be great....after 4+ years

**Comment by timwsuqld** [comment]
Hey everyone. This is an open source project. If someone has resources they can put towards making this happen, then great. Otherwise, there is a [bug bunty](https://www.bountysource.com/issues/8712905-saml-is-there-any-easy-way-to-implement-it-with-snipe-it?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github) that you can put money towards making this happen. If you want to have a look at implementing it, maybe start by looking at Laravel SAML bundles (like https://github.com/aacotroneo/laravel-saml2)

Getting upset that this hasn't been implemented in a free product, isn't going to get it implemented.

Also, one option for those who can't wait may be Shibboleth with SAML login populating the REMOTE_USER environment variable.

**Comment by snipe** [comment]
@josephvaughan 

> another +1 for SAML. What kind of help do you need to get this done?

Literally a way to test it. It's what we've always needed.

**Comment by snipe** [comment]
(Also seeing lots of Okta folks here - Snipe-IT works great with the LDAP login integration, and has for some time.)

**Comment by ReillyProcentive** [comment]
Most (all?) of the IDP platforms offer free accounts for developers:
[Okta](https://www.okta.com/api/signup/FRT/)
[OneLogin](https://www.onelogin.com/developer-signup)
[Azure AD](https://azure.microsoft.com/en-us/pricing/details/active-directory/)

**Comment by grantemsley** [comment]
Yes, this issue is still relevant.  Many of us would love to use SAML for authentication.

**Comment by webbexpert** [comment]
Definitely not stale - I've been watching this one like a hawk. If I had more free time I would just submit a PR; setting up snipe-it as a SAML 2 Service Provider (SP) would be a huge improvement for security purposes. SAML is turning into a very well accepted setup for B2B apps

**Comment by ndarwincorn** [comment]
@snipe - I've got a working demo (for IdP-initiated SAML, at any rate, so about half of what all the folks making demands in here want) with the [aacotroneo/laravel-saml2 library](https://github.com/aacotroneo/laravel-saml2) using a local [samling](https://github.com/capriza/samling) instance to test.

If you're interested I'll get it organized better and open a PR. I don't think it'd be that difficult to write a Mink test using [samling's GH page](https://capriza.github.io/samling/samling.html) as a test IdP.

**Comment by amnya** [comment]
> @snipe - I've got a working demo (for IdP-initiated SAML, at any rate, so about half of what all the folks making demands in here want) with the [aacotroneo/laravel-saml2 library](https://github.com/aacotroneo/laravel-saml2) using a local [samling](https://github.com/capriza/samling) instance to test.
> 
> If you're interested I'll get it organized better and open a PR. I don't think it'd be that difficult to write a Mink test using [samling's GH page](https://capriza.github.io/samling/samling.html) as a test IdP.

Hello dear,
I am very interested in this and would love to have it implemented. I was about to buy a hosted plan with Snipe-IT, but since SAML is not there, i am keeping it on hold until we see this working with SAML. This is a security prerequisite to me and wont be buying the product without it.

Much appreciated if you can help us with this.

**Comment by ndarwincorn** [comment]
@amnya - going to make this explicit since you didn't pick it up from the
rest of the thread: my question was for the maintainers, NOT customers
(much less potential ones). If the hosted snipe product is within your
budget you can afford to pay the bounty to get this feature implemented.

-Darwin

**Comment by innocuoussoul** [comment]
Is there a bounty for this? SAML is essentially the reason why I can’t implement hosted snipe, but I really don’t want to maintain the server in Orem.

**Comment by amnya** [comment]
Hey Darwin, thank you for your message. what is the bounty amount if you implement it for my insurance? And can it be implemented on the SaaS model of snipe-it? Thanks dear.

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 22, 2019 at 12:07 AM, innocuoussoul<notifications@github.com> wrote:   
Is there a bounty for this? SAML is essentially the reason why I can’t implement hosted snipe, but I really don’t want to maintain the server in Orem.

**Comment by innocuoussoul** [comment]
@ndarwincorn what is the current bounty?

**Comment by ndarwincorn** [comment]
@innocuoussoul @amnya: First, you two should review [some guidelines on being good open source citizens](https://hugh.blog/2019/03/15/becoming-a-good-open-source-citizen/). I'm muting this thread, and it's your non-constructive comments that I'm unsubbing from.

After you read that, I've got two points to clarify:

1. You are welcome to put the bounty of how much you'd contribute to getting this implemented in the [link at the top of this page](https://www.bountysource.com/issues/8712905-saml-is-there-any-easy-way-to-implement-it-with-snipe-it?utm_campaign=plugin&utm_content=tracker%2F505106&utm_medium=issues&utm_source=github). If you follow that link, you'll see that the current bounty is $0. Rather than ask me what the bounty is, determine how much you'd contribute monetarily to someone who would implement this feature, and become a backer in that Bountysource link.

2. I'm not a contributor to this project, and I have 0 control of what features make it into the hosted instance of the software. The quick patch I implemented to get **one half** (IdP-initiated) of a robust SAML flow implemented in our fork would probably not be welcome upstream (hence my question to the maintainer(s) asking whether a more robust version would be welcome--they're the ones that have to support it, not me). If I hear back from a maintainer, I may do that leg work. But I'm certainly not going to do it if it's not wanted.

**Comment by webbexpert** [comment]
Not stale -- Our team is watching this thread like a hawk. Were considering moving to another inventory tool due to lack of SSO support

In a previous post I outlined the feature request in detail

**Comment by mwl** [comment]
SAML and single-on in general is still very relevant to us. Means less account administration.

**Comment by jsheridan1** [comment]
Still relevant for us as well.  We are using the paid hosted version.

**Comment by StarWhiz** [comment]
SAML is still relevant for me as well.

**Comment by leifbraeg** [comment]
Also very much interested in this.

**Comment by knetherton-Taxslayer** [comment]
Our company is hoping to get forced SSO so that we can adopt your product.  BTW, you're selling yourself short.  We would pay 5-10 times what you're charging for a good hosted tool.  Key is that we have to have forced SSO (no password login option except for admin account).

**Comment by gezakukoda** [comment]
+1 for SSO/SAML

**Comment by FletcherS7** [comment]
Another +1 for SAML

**Comment by tstrohmeier** [comment]
+1 for SAML or OIDC

**Comment by angel-pantoja** [comment]
+SAML

**Comment by ewancolyer** [comment]
Instead of everyone doing +1, place a bug bounty on it or open a PR with your contribution!

**Comment by pitbulk** [comment]
@snipe I'm trying to contact you via Linkedin and see if we can agree on something to provide SAML support to snipe-it.

**Comment by sargonas** [comment]
bumping this for vis... if the pull request from @pitbulk up above is to unlock standard saml support for things like Okta we are VERY interested in this. Working to roll out snipe into prod, but right now we're having issues with LDAP over Okta breaking randomly from time to time for no known reason due to the LDAP work around, and this would help with that greatly.

**Comment by innocuoussoul** [comment]
Heads up there was a PR approved for some saml support in the develop branch! Not sure if it will work with Okta yet, but it’s using onelogin’s php-saml package.

**Comment by davidbwashburn** [comment]
SAML to Azure AD would make this guy very happy. All of you working on this real international heroes.

**Comment by Wartz** [comment]
SAML is a huge feature that would make my life a lot easier! Thanks to the people working on it.

**Comment by pitbulk** [comment]
Yes I wanted to implement a standard SAML support (not the shibboleth trick / $USER I saw) 

this commit already has the approach I had in mind:
https://github.com/snipe/snipe-it/commit/c3d8024e1fc80982f7408fa590418df8e4ed9181

**Comment by karthik5003** [comment]
+1 for SAML

**Comment by tholu** [comment]
@webbexpert Have you moved to a different tool or are you also still waiting for this?

**Comment by yosiasz** [comment]
@tholu We are still waiting for SSO SAML implementation. It will be a deal breaker for us if we cannot have this, for hosted services at least.

**Comment by fstorz** [comment]
@snipe Is this issue about to be closed? The corresponding PR (#8023) to add SAML support was merged already to develop. Is this issue then related to milestone "v5"?

**Comment by Aiv114** [comment]
+1 SAML

**Comment by adagioajanes** [comment]
+1 for SAML

**Comment by ReillyTevera** [comment]
@adagioajanes Did you even bother to read this thread before making a useless and unhelpful comment? SAML support has already been merged and will be in the next major release of Snipe-IT.

**Comment by adagioajanes** [comment]
> @adagioajanes Did you even bother to read this thread before making a useless and unhelpful comment? SAML support has already been merged and will be in the next major release of Snipe-IT.

I saw this issue was still open. Therefor I assumed it was not implemented, as I can't find documentation for it.

No need to be rude about it.

**Comment by ajf15cc** [comment]
> > @adagioajanes Did you even bother to read this thread before making a useless and unhelpful comment? SAML support has already been merged and will be in the next major release of Snipe-IT.
> 
> I saw this issue was still open. Therefor I assumed it was not implemented, as I can't find documentation for it.
> 
> No need to be rude about it.


Its also not included here: https://snipeitapp.com/blog/snipe-it-v5.0-progress-oct 

<blockquote><div><strong><a href="https://snipeitapp.com/blog/snipe-it-v5.0-progress-oct">Snipe-IT v5 update - Snipe-IT Open Source IT Asset Management</a></strong></div><div>Just a quickie update on what we've gotten done so far in the upcoming v5 (currently on the `develop` branch). Lots of stuff is changed under the hood, as we've upgraded the underlying framework to La...</div></blockquote>

**Comment by fstorz** [comment]
@snipe As v5 was released (again thanks for that) the SAML support is now available in code. But there is some documentation missing. I setup SAML with my installation and could help out with the docu. But I'm not sure where I can contribute the text and images. Is this possible via readme.io?

**Comment by fstorz** [comment]
SO maybe I will start documenting here :D

## General steps to do:
* Configure SAML values at IDP (Entity-ID, Assertion Consumer Service (ACS) URL, Single Logout Service (SLS) URL)
* Download IdP Metadata / Get IdP Metadata URL
* Upload IdP Metadatafile / Paste IdP Metadata URL to Snipe-IT SAML settings
* If necessary, add additional custom config to Snipe-IT SAML settings

## IdP SAML Configuration Values
There are many pages out there on how to configure the following values for your IdP. 
We use AzureAD and there is some basic [example from Microsoft](https://docs.microsoft.com/en-gb/azure/active-directory/saas-apps/samlssoconfluence-tutorial). 

* **Entity-ID:** https://assets.example.com
* **Assertion Consumer Service (ACS) URL:** https://assets.example.com/saml/acs
* **Single Logout Service (SLS) URL:** https://assets.example.com/saml/sls
* Configure also a certificate at IdP, which is used to sign the SAML Responses

Azure will automatically configure a certificate for you to sign the SAML responses when you click on the "add certificate" link.

## Snipe-IT SAML Settings
### Attribute Mapping - Username
It is possible to override the default setting, to use the value from the "NameID" response element to match against the username of existing users. If your IdP uses another element in the SAML response, set the value here. 

Relevant example from SAML response 
```
<Subject>
    <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">email.address@example.com</NameID>
    <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <SubjectConfirmationData InResponseTo="ONELOGIN_..." NotOnOrAfter="2020-10-01T00:00:00.000Z" Recipient="https://assets.example.com/saml/acs"/>
    </SubjectConfirmation>
</Subject>
```

If you have existing users configured in Snipe-IT, make sure that their *usernames* match the value of the NameID element!

### SAML Force Login
When this checkbox is enabled, you will not see a login form of Snipe-IT anymore when you go to the Snipe-IT website. Instead it will redirect you directly to the IdP SAML Login.
When you need to see the login form of Snipe-IT to login with an existing user without SAML login, you could add the following query parameter to your Snipe-IT URL: _/login?nosaml_ -> _https://assets.example.com/login?nosaml_. This might be useful when there are some technical problems with your IdP to be able to sill login to Snipe-IT. For this scenario, make sure that there is an "admin" user in the Snipe-IT user database, who does not login via SAML.

### SAML Single Log Out
When this checkbox is enabled, then Snipe-IT will send a logout request to your IdP when you click on the Logout Button in Snipe-IT.
This will cause the user to be first redirected to the IdP on logout. Leave unchecked if the IdP doesn't correctly support SP-initiated SAML SLO.

### SAML Custom Settings
Here you can add custom settings to adjust the configuration of the underlaying library which provides the SAML functionality.
Values are defined as key-value pairs like the following: _key=value_

Config values are (maybe some are missing) ([Source](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php))
* strict=true|false
* baseurl=...
* debug=true|false
* sp.anySpConfig=...
* idp.anyIdpConfig=...
* security.anySecurityConfig=...

When you run Snipe-IT behind a reverse proxy the following property might be necessary: _baseurl=https://assets.example.com/saml_

## Debug SAML Response
When you need to check the SAML response which is received by Snipe-IT, a simiple woraround might be to use the developer tools of your browser. 
After configuring your SAML config in Snipe-IT, just go to an incognito tab, open the devloper tools (mostly with F12) and go to the "network" tab. Now open your Snipe-IT website and wait that the login of your IdP is shown. Login in with your IdP credentials and wait until you are redirected back to your Snipe-IT. 
Now check the entries of your developer tools "network" tab.  There should be an entry for "acs" or "saml/acs", which represents the redirect from your IdP to your callback URL which includes the SAML Response as body parameter. So click on the entry and scroll down in the entry's details to the request body and copy the value of the parameter _SAMLResponse_. 
The value is base64 encoded, so find a tool which could decode it (I would not suggest to do this online, because the value contains a valid access token for your user at your IdP!). When you have decoded it you have the SAML response in XML format :)

Hint: Works in Google Chrome, and mabye others work the same way

**Comment by boyejoayo** [comment]
This is looking interesting...

**Comment by denzfarid** [comment]
> SO maybe I will start documenting here :D
> ## General steps to do:
> 
>     * Configure SAML values at IDP (Entity-ID, Assertion Consumer Service (ACS) URL, Single Logout Service (SLS) URL)
> 
>     * Download IdP Metadata / Get IdP Metadata URL
> 
>     * Upload IdP Metadatafile / Paste IdP Metadata URL to Snipe-IT SAML settings
> 
>     * If necessary, add additional custom config to Snipe-IT SAML settings
> 
> 
> ## IdP SAML Configuration Values
> 
> There are many pages out there on how to configure the following values for your IdP.
> We use AzureAD and there is some basic [example from Microsoft](https://docs.microsoft.com/en-gb/azure/active-directory/saas-apps/samlssoconfluence-tutorial).
> 
>     * **Entity-ID:** https://assets.example.com
> 
>     * **Assertion Consumer Service (ACS) URL:** https://assets.example.com/saml/acs
> 
>     * **Single Logout Service (SLS) URL:** https://assets.example.com/saml/sls
> 
>     * Configure also a certificate at IdP, which is used to sign the SAML Responses
> 
> 
> Azure will automatically configure a certificate for you to sign the SAML responses when you click on the "add certificate" link.
> ## Snipe-IT SAML Settings
> ### Attribute Mapping - Username
> 
> It is possible to override the default setting, to use the value from the "NameID" response element to match against the username of existing users. If your IdP uses another element in the SAML response, set the value here.
> 
> Relevant example from SAML response
> 
> ```
> <Subject>
>     <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">email.address@example.com</NameID>
>     <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
>         <SubjectConfirmationData InResponseTo="ONELOGIN_..." NotOnOrAfter="2020-10-01T00:00:00.000Z" Recipient="https://assets.example.com/saml/acs"/>
>     </SubjectConfirmation>
> </Subject>
> ```
> 
> If you have existing users configured in Snipe-IT, make sure that their _usernames_ match the value of the NameID element!
> ### SAML Force Login
> 
> When this checkbox is enabled, you will not see a login form of Snipe-IT anymore when you go to the Snipe-IT website. Instead it will redirect you directly to the IdP SAML Login.
> When you need to see the login form of Snipe-IT to login with an existing user without SAML login, you could add the following query parameter to your Snipe-IT URL: _/login?nosaml_ -> _https://assets.example.com/login?nosaml_. This might be useful when there are some technical problems with your IdP to be able to sill login to Snipe-IT. For this scenario, make sure that there is an "admin" user in the Snipe-IT user database, who does not login via SAML.
> ### SAML Single Log Out
> 
> When this checkbox is enabled, then Snipe-IT will send a logout request to your IdP when you click on the Logout Button in Snipe-IT.
> This will cause the user to be first redirected to the IdP on logout. Leave unchecked if the IdP doesn't correctly support SP-initiated SAML SLO.
> ### SAML Custom Settings
> 
> Here you can add custom settings to adjust the configuration of the underlaying library which provides the SAML functionality.
> Values are defined as key-value pairs like the following: _key=value_
> 
> Config values are (maybe some are missing) ([Source](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php))
> 
>     * strict=true|false
> 
>     * baseurl=...
> 
>     * debug=true|false
> 
>     * sp.anySpConfig=...
> 
>     * idp.anyIdpConfig=...
> 
>     * security.anySecurityConfig=...
> 
> 
> When you run Snipe-IT behind a reverse proxy the following property might be necessary: _baseurl=https://assets.example.com/saml_
> ## Debug SAML Response
> 
> When you need to check the SAML response which is received by Snipe-IT, a simiple woraround might be to use the developer tools of your browser.
> After configuring your SAML config in Snipe-IT, just go to an incognito tab, open the devloper tools (mostly with F12) and go to the "network" tab. Now open your Snipe-IT website and wait that the login of your IdP is shown. Login in with your IdP credentials and wait until you are redirected back to your Snipe-IT.
> Now check the entries of your developer tools "network" tab. There should be an entry for "acs" or "saml/acs", which represents the redirect from your IdP to your callback URL which includes the SAML Response as body parameter. So click on the entry and scroll down in the entry's details to the request body and copy the value of the parameter _SAMLResponse_.
> The value is base64 encoded, so find a tool which could decode it (I would not suggest to do this online, because the value contains a valid access token for your user at your IdP!). When you have decoded it you have the SAML response in XML format :)
> 
> Hint: Works in Google Chrome, and mabye others work the same way

thanks man! I really appreciate,
I use this method on the gsuite, but there are a few changes, before you mentioned this

`make sure that their usernames match the value of the NameID element!`

and finally I changed username = email,
and it's working

The following is the SQL syntax for changing the username to the same as email
```sql
update users set username=email
```

**Comment by snipe** [comment]
We have this documented here now: https://snipe-it.readme.io/docs/saml


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/saml">SAML</a></strong></div><div>Configuration guidelines for SAML Single-Sign On (SSO) support</div></blockquote>
